### ISSUE TITLE
Page hangs without any information when JWT expires

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#142]
When the JWT expires, any requests made become unresponsive without any feedback - the user is not aware that they need to log out and then log in again to obtain a new JWT to be able to use the CMS. 

What we can be doing in this situation: 
- Re-login for them automatically 
- Automatically log them out with an error message saying that their session has expired and redirect them to the login page

If we decide to log them out automatically, we can create a higher-order component to handle the auto-logout as we did for Homer dashboard.

Something that we might want to consider is whether we should store any work that is in progress on local storage in case they've been working on something and they forgot to save it. In any case we might also want to extend the auth token expiry value as a form of mitigation. 

### Details

When this occurs, all we get on the frontend is this:

```
GET http://localhost:8081/sites/covid-info/pages 400 (Bad Request)
```

This is the log from the backend:

```
GET /sites/covid-info/pages 400 16.649 ms - 91
{ TokenExpiredError: jwt expired
    at /Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/jsonwebtoken/verify.js:152:21
    at getSecret (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/jsonwebtoken/verify.js:90:14)
    at module.exports (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/jsonwebtoken/verify.js:94:10)
    at Object.jwtUtil.verifyToken._.wrap (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/utils/jwt-utils.js:10:24)
    at apply (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/lodash/lodash.js:475:27)
    at Object.wrapper [as verifyToken] (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/lodash/lodash.js:5317:16)
    at /Users/jiehaokwa/Documents/isomercms/isomercms-backend/routes/pages.js:15:39
    at Layer.handle [as handle_request] (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/express/lib/router/layer.js:95:5)
    at /Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/express/lib/router/index.js:281:22
    at param (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/jiehaokwa/Documents/isomercms/isomercms-backend/node_modules/express/lib/router/index.js:275:10)
  name: 'TokenExpiredError',
  message: 'jwt expired',
  expiredAt: 2020-10-07T08:25:56.000Z }
```

**Comment by kwajiehao** [comment]
Duplicate issue with #156
